bind_addr = ":3000"
cors_allowed_origins = [ "http://localhost:8000" ]
cors_allowed_methods = [ "GET", "POST", "PUT", "OPTIONS" ]
cors_allowed_headers = [ "X-Requested-With", "Content-Type" ]

[store]
database_url = "root:123456@tcp(host.docker.internal:3306)/interest_points"